import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Viewport } from "@/components/viewport";
import { SoundEffects } from "@/components/sfx";
import { ClickToEnter } from "@/components/click-to-enter";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full w-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-full w-full crt`}
      >
        <ClickToEnter>
          <SoundEffects />
          <Viewport>{children}</Viewport>
        </ClickToEnter>
      </body>
    </html>
  );
}
